name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Run Setup
        run: |
          make cairo-install
        id: setup
      - name: Display cairo version
        run: source venv/bin/activate && cairo-run --version
      - name: Run Script
        run: |
          source venv/bin/activate && make fetch-input
        id: script
      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
